/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API - Authentication
 * REST API для автентифікації користувачів.

⚠️ **Note**: Всі інші endpoints доступні через GraphQL API. Використовуйте GraphiQL Playground на `/graphql` для GraphQL API документації.
 * OpenAPI spec version: 1.0.0
 */

export type GetApiAuthGoogleCallback400 = {
  success?: boolean;
  message?: string;
};
