/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API
 * Modern backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMe200OneData } from "./getApiMe200OneData";

export type GetApiMe200One = {
  success: boolean;
  message: string;
  data: GetApiMe200OneData;
};
