/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API - Authentication
 * REST API для автентифікації користувачів.

⚠️ **Note**: Всі інші endpoints доступні через GraphQL API. Використовуйте GraphiQL Playground на `/graphql` для GraphQL API документації.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMe200DataUser } from './getApiMe200DataUser';

export type GetApiMe200Data = {
  user?: GetApiMe200DataUser;
};
