/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API Documentation
 * Production-ready backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { GetAuthMe200Data } from "./getAuthMe200Data";

export type GetAuthMe200 = {
  success?: boolean;
  message?: string;
  data?: GetAuthMe200Data;
};
