/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API
 * Modern backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.

⚠️ **Note**: GraphQL endpoints are not included in this REST API documentation. Use GraphiQL Playground at `/graphql` for GraphQL API documentation.
 * OpenAPI spec version: 1.0.0
 */

export type GetFeedSort = typeof GetFeedSort[keyof typeof GetFeedSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetFeedSort = {
  best: 'best',
  hot: 'hot',
  new: 'new',
  rising: 'rising',
  top: 'top',
} as const;
