/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API
 * Modern backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.
 * OpenAPI spec version: 1.0.0
 */

export type PostApiLogout200 = {
  success?: boolean;
  message?: string;
};
