/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API Documentation
 * Production-ready backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthRegister409Data } from "./postAuthRegister409Data";

export type PostAuthRegister409 = {
  success?: boolean;
  message?: string;
  /** @nullable */
  data?: PostAuthRegister409Data;
};
