/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Reddit Backend API - Authentication
 * REST API для автентифікації користувачів.

⚠️ **Note**: Всі інші endpoints доступні через GraphQL API. Використовуйте GraphiQL Playground на `/graphql` для GraphQL API документації.
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthRegister201Data } from './postAuthRegister201Data';

export type PostAuthRegister201 = {
  success?: boolean;
  message?: string;
  data?: PostAuthRegister201Data;
};
