/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API
 * Modern backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.
 * OpenAPI spec version: 1.0.0
 */

export type PostApiRegisterBodyOne = {
  /**
   * @minLength 3
   * @maxLength 30
   * @pattern ^[a-zA-Z0-9_]+$
   */
  username: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @minLength 6 */
  password: string;
};
