/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API
 * Modern backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiLogin400Data } from "./postApiLogin400Data";

export type PostApiLogin400 = {
  success?: boolean;
  message?: string;
  /** @nullable */
  data?: PostApiLogin400Data;
};
