/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API Documentation
 * Production-ready backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterRequest {
  /**
   * @minLength 3
   * @maxLength 30
   * @pattern ^[a-zA-Z0-9_]+$
   */
  username: string;
  email: string;
  /**
   * @minLength 8
   * @maxLength 100
   */
  password: string;
}
