/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API
 * Modern backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.

⚠️ **Note**: GraphQL endpoints are not included in this REST API documentation. Use GraphiQL Playground at `/graphql` for GraphQL API documentation.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCommentsPostByPostIdParams,
  PostCommentsPostByPostIdBodyOne,
  PutCommentsByIdVoteBodyOne
} from '../../models';

import { apiMutator } from '../../apiMutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieves paginated comments for a specific post in tree structure
 * @summary Get comments for post
 */
export type getCommentsPostByPostIdResponseDefault = {
  data: unknown
  status: number
}
    
;
export type getCommentsPostByPostIdResponseError = (getCommentsPostByPostIdResponseDefault) & {
  headers: Headers;
};

export type getCommentsPostByPostIdResponse = (getCommentsPostByPostIdResponseError)

export const getGetCommentsPostByPostIdUrl = (postId: string,
    params?: GetCommentsPostByPostIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/comments/post/${postId}?${stringifiedParams}` : `/comments/post/${postId}`
}

export const getCommentsPostByPostId = async (postId: string,
    params?: GetCommentsPostByPostIdParams, options?: RequestInit): Promise<getCommentsPostByPostIdResponse> => {
  
  return apiMutator<getCommentsPostByPostIdResponse>(getGetCommentsPostByPostIdUrl(postId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetCommentsPostByPostIdQueryKey = (postId?: string,
    params?: GetCommentsPostByPostIdParams,) => {
    return [
    `/comments/post/${postId}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCommentsPostByPostIdQueryOptions = <TData = Awaited<ReturnType<typeof getCommentsPostByPostId>>, TError = unknown>(postId: string,
    params?: GetCommentsPostByPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentsPostByPostId>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCommentsPostByPostIdQueryKey(postId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCommentsPostByPostId>>> = ({ signal }) => getCommentsPostByPostId(postId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCommentsPostByPostId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCommentsPostByPostIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCommentsPostByPostId>>>
export type GetCommentsPostByPostIdQueryError = unknown


export function useGetCommentsPostByPostId<TData = Awaited<ReturnType<typeof getCommentsPostByPostId>>, TError = unknown>(
 postId: string,
    params: undefined |  GetCommentsPostByPostIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentsPostByPostId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCommentsPostByPostId>>,
          TError,
          Awaited<ReturnType<typeof getCommentsPostByPostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCommentsPostByPostId<TData = Awaited<ReturnType<typeof getCommentsPostByPostId>>, TError = unknown>(
 postId: string,
    params?: GetCommentsPostByPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentsPostByPostId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCommentsPostByPostId>>,
          TError,
          Awaited<ReturnType<typeof getCommentsPostByPostId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCommentsPostByPostId<TData = Awaited<ReturnType<typeof getCommentsPostByPostId>>, TError = unknown>(
 postId: string,
    params?: GetCommentsPostByPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentsPostByPostId>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get comments for post
 */

export function useGetCommentsPostByPostId<TData = Awaited<ReturnType<typeof getCommentsPostByPostId>>, TError = unknown>(
 postId: string,
    params?: GetCommentsPostByPostIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentsPostByPostId>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCommentsPostByPostIdQueryOptions(postId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Creates a new comment on a post
 * @summary Create comment
 */
export type postCommentsPostByPostIdResponseDefault = {
  data: unknown
  status: number
}
    
;
export type postCommentsPostByPostIdResponseError = (postCommentsPostByPostIdResponseDefault) & {
  headers: Headers;
};

export type postCommentsPostByPostIdResponse = (postCommentsPostByPostIdResponseError)

export const getPostCommentsPostByPostIdUrl = (postId: string,) => {


  

  return `/comments/post/${postId}`
}

export const postCommentsPostByPostId = async (postId: string,
    postCommentsPostByPostIdBodyOne: PostCommentsPostByPostIdBodyOne, options?: RequestInit): Promise<postCommentsPostByPostIdResponse> => {
  
  return apiMutator<postCommentsPostByPostIdResponse>(getPostCommentsPostByPostIdUrl(postId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postCommentsPostByPostIdBodyOne,)
  }
);}




export const getPostCommentsPostByPostIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCommentsPostByPostId>>, TError,{postId: string;data: PostCommentsPostByPostIdBodyOne}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postCommentsPostByPostId>>, TError,{postId: string;data: PostCommentsPostByPostIdBodyOne}, TContext> => {

const mutationKey = ['postCommentsPostByPostId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCommentsPostByPostId>>, {postId: string;data: PostCommentsPostByPostIdBodyOne}> = (props) => {
          const {postId,data} = props ?? {};

          return  postCommentsPostByPostId(postId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostCommentsPostByPostIdMutationResult = NonNullable<Awaited<ReturnType<typeof postCommentsPostByPostId>>>
    export type PostCommentsPostByPostIdMutationBody = PostCommentsPostByPostIdBodyOne
    export type PostCommentsPostByPostIdMutationError = unknown

    /**
 * @summary Create comment
 */
export const usePostCommentsPostByPostId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCommentsPostByPostId>>, TError,{postId: string;data: PostCommentsPostByPostIdBodyOne}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postCommentsPostByPostId>>,
        TError,
        {postId: string;data: PostCommentsPostByPostIdBodyOne},
        TContext
      > => {

      const mutationOptions = getPostCommentsPostByPostIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Upvote or downvote a comment
 * @summary Vote on comment
 */
export type putCommentsByIdVoteResponseDefault = {
  data: unknown
  status: number
}
    
;
export type putCommentsByIdVoteResponseError = (putCommentsByIdVoteResponseDefault) & {
  headers: Headers;
};

export type putCommentsByIdVoteResponse = (putCommentsByIdVoteResponseError)

export const getPutCommentsByIdVoteUrl = (id: string,) => {


  

  return `/comments/${id}/vote`
}

export const putCommentsByIdVote = async (id: string,
    putCommentsByIdVoteBodyOne: PutCommentsByIdVoteBodyOne, options?: RequestInit): Promise<putCommentsByIdVoteResponse> => {
  
  return apiMutator<putCommentsByIdVoteResponse>(getPutCommentsByIdVoteUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putCommentsByIdVoteBodyOne,)
  }
);}




export const getPutCommentsByIdVoteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putCommentsByIdVote>>, TError,{id: string;data: PutCommentsByIdVoteBodyOne}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putCommentsByIdVote>>, TError,{id: string;data: PutCommentsByIdVoteBodyOne}, TContext> => {

const mutationKey = ['putCommentsByIdVote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putCommentsByIdVote>>, {id: string;data: PutCommentsByIdVoteBodyOne}> = (props) => {
          const {id,data} = props ?? {};

          return  putCommentsByIdVote(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutCommentsByIdVoteMutationResult = NonNullable<Awaited<ReturnType<typeof putCommentsByIdVote>>>
    export type PutCommentsByIdVoteMutationBody = PutCommentsByIdVoteBodyOne
    export type PutCommentsByIdVoteMutationError = unknown

    /**
 * @summary Vote on comment
 */
export const usePutCommentsByIdVote = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putCommentsByIdVote>>, TError,{id: string;data: PutCommentsByIdVoteBodyOne}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putCommentsByIdVote>>,
        TError,
        {id: string;data: PutCommentsByIdVoteBodyOne},
        TContext
      > => {

      const mutationOptions = getPutCommentsByIdVoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    