/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API
 * Modern backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { PostApiLoginBodyOne, PostApiRegisterBodyOne } from "../../models";

import { apiMutator } from "../../apiMutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Register a new user
 */
export type postApiRegisterResponse200 = {
  data: void;
  status: 200;
};

export type postApiRegisterResponseSuccess = postApiRegisterResponse200 & {
  headers: Headers;
};
export type postApiRegisterResponse = postApiRegisterResponseSuccess;

export const getPostApiRegisterUrl = () => {
  return `/api/register`;
};

export const postApiRegister = async (
  postApiRegisterBodyOne: PostApiRegisterBodyOne,
  options?: RequestInit,
): Promise<postApiRegisterResponse> => {
  return apiMutator<postApiRegisterResponse>(getPostApiRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postApiRegisterBodyOne),
  });
};

export const getPostApiRegisterMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiRegister>>,
    TError,
    { data: PostApiRegisterBodyOne },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiRegister>>,
  TError,
  { data: PostApiRegisterBodyOne },
  TContext
> => {
  const mutationKey = ["postApiRegister"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiRegister>>,
    { data: PostApiRegisterBodyOne }
  > = (props) => {
    const { data } = props ?? {};

    return postApiRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiRegister>>
>;
export type PostApiRegisterMutationBody = PostApiRegisterBodyOne;
export type PostApiRegisterMutationError = unknown;

/**
 * @summary Register a new user
 */
export const usePostApiRegister = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiRegister>>,
      TError,
      { data: PostApiRegisterBodyOne },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiRegister>>,
  TError,
  { data: PostApiRegisterBodyOne },
  TContext
> => {
  const mutationOptions = getPostApiRegisterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Login user
 */
export type postApiLoginResponse200 = {
  data: void;
  status: 200;
};

export type postApiLoginResponseSuccess = postApiLoginResponse200 & {
  headers: Headers;
};
export type postApiLoginResponse = postApiLoginResponseSuccess;

export const getPostApiLoginUrl = () => {
  return `/api/login`;
};

export const postApiLogin = async (
  postApiLoginBodyOne: PostApiLoginBodyOne,
  options?: RequestInit,
): Promise<postApiLoginResponse> => {
  return apiMutator<postApiLoginResponse>(getPostApiLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postApiLoginBodyOne),
  });
};

export const getPostApiLoginMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiLogin>>,
    TError,
    { data: PostApiLoginBodyOne },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiLogin>>,
  TError,
  { data: PostApiLoginBodyOne },
  TContext
> => {
  const mutationKey = ["postApiLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiLogin>>,
    { data: PostApiLoginBodyOne }
  > = (props) => {
    const { data } = props ?? {};

    return postApiLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiLogin>>
>;
export type PostApiLoginMutationBody = PostApiLoginBodyOne;
export type PostApiLoginMutationError = unknown;

/**
 * @summary Login user
 */
export const usePostApiLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiLogin>>,
      TError,
      { data: PostApiLoginBodyOne },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiLogin>>,
  TError,
  { data: PostApiLoginBodyOne },
  TContext
> => {
  const mutationOptions = getPostApiLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Logs out the current user by destroying their session and clearing the session cookie.
 * @summary Logout user
 */
export type postApiLogoutResponse200 = {
  data: void;
  status: 200;
};

export type postApiLogoutResponseSuccess = postApiLogoutResponse200 & {
  headers: Headers;
};
export type postApiLogoutResponse = postApiLogoutResponseSuccess;

export const getPostApiLogoutUrl = () => {
  return `/api/logout`;
};

export const postApiLogout = async (
  options?: RequestInit,
): Promise<postApiLogoutResponse> => {
  return apiMutator<postApiLogoutResponse>(getPostApiLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const getPostApiLogoutMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiLogout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postApiLogout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiLogout>>,
    void
  > = () => {
    return postApiLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiLogout>>
>;

export type PostApiLogoutMutationError = unknown;

/**
 * @summary Logout user
 */
export const usePostApiLogout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiLogout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPostApiLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves the currently authenticated user's information based on their session cookie.
 * @summary Get current user
 */
export type getApiMeResponse200 = {
  data: void;
  status: 200;
};

export type getApiMeResponseSuccess = getApiMeResponse200 & {
  headers: Headers;
};
export type getApiMeResponse = getApiMeResponseSuccess;

export const getGetApiMeUrl = () => {
  return `/api/me`;
};

export const getApiMe = async (
  options?: RequestInit,
): Promise<getApiMeResponse> => {
  return apiMutator<getApiMeResponse>(getGetApiMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetApiMeQueryKey = () => {
  return [`/api/me`] as const;
};

export const getGetApiMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof apiMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({
    signal,
  }) => getApiMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiMe>>
>;
export type GetApiMeQueryError = unknown;

export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user
 */

export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
