/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API - Authentication
 * REST API для автентифікації користувачів.

⚠️ **Note**: Всі інші endpoints доступні через GraphQL API. Використовуйте GraphiQL Playground на `/graphql` для GraphQL API документації.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiAuthGoogleCallback400,
  GetApiAuthGoogleCallback401,
  GetApiAuthGoogleCallback500,
  GetAuthMe200,
  GetAuthMe401,
  GetAuthMe500,
  PostAuthLogin200,
  PostAuthLogin401,
  PostAuthLogin500,
  PostAuthLoginBodyOne,
  PostAuthLogout200,
  PostAuthLogout500,
  PostAuthRegister201,
  PostAuthRegister400,
  PostAuthRegister409,
  PostAuthRegister500,
  PostAuthRegisterBodyOne
} from '../../models';

import { apiMutator } from '../../apiMutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Register and login user
 */
export type postAuthRegisterResponse201 = {
  data: PostAuthRegister201
  status: 201
}

export type postAuthRegisterResponse400 = {
  data: PostAuthRegister400
  status: 400
}

export type postAuthRegisterResponse409 = {
  data: PostAuthRegister409
  status: 409
}

export type postAuthRegisterResponse500 = {
  data: PostAuthRegister500
  status: 500
}
    
export type postAuthRegisterResponseSuccess = (postAuthRegisterResponse201) & {
  headers: Headers;
};
export type postAuthRegisterResponseError = (postAuthRegisterResponse400 | postAuthRegisterResponse409 | postAuthRegisterResponse500) & {
  headers: Headers;
};

export type postAuthRegisterResponse = (postAuthRegisterResponseSuccess | postAuthRegisterResponseError)

export const getPostAuthRegisterUrl = () => {


  

  return `/auth/register`
}

export const postAuthRegister = async (postAuthRegisterBodyOne: PostAuthRegisterBodyOne, options?: RequestInit): Promise<postAuthRegisterResponse> => {
  
  return apiMutator<postAuthRegisterResponse>(getPostAuthRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postAuthRegisterBodyOne,)
  }
);}




export const getPostAuthRegisterMutationOptions = <TError = PostAuthRegister400 | PostAuthRegister409 | PostAuthRegister500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: PostAuthRegisterBodyOne}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: PostAuthRegisterBodyOne}, TContext> => {

const mutationKey = ['postAuthRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRegister>>, {data: PostAuthRegisterBodyOne}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRegister(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRegister>>>
    export type PostAuthRegisterMutationBody = PostAuthRegisterBodyOne
    export type PostAuthRegisterMutationError = PostAuthRegister400 | PostAuthRegister409 | PostAuthRegister500

    /**
 * @summary Register and login user
 */
export const usePostAuthRegister = <TError = PostAuthRegister400 | PostAuthRegister409 | PostAuthRegister500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: PostAuthRegisterBodyOne}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRegister>>,
        TError,
        {data: PostAuthRegisterBodyOne},
        TContext
      > => {

      const mutationOptions = getPostAuthRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Login user
 */
export type postAuthLoginResponse200 = {
  data: PostAuthLogin200
  status: 200
}

export type postAuthLoginResponse401 = {
  data: PostAuthLogin401
  status: 401
}

export type postAuthLoginResponse500 = {
  data: PostAuthLogin500
  status: 500
}
    
export type postAuthLoginResponseSuccess = (postAuthLoginResponse200) & {
  headers: Headers;
};
export type postAuthLoginResponseError = (postAuthLoginResponse401 | postAuthLoginResponse500) & {
  headers: Headers;
};

export type postAuthLoginResponse = (postAuthLoginResponseSuccess | postAuthLoginResponseError)

export const getPostAuthLoginUrl = () => {


  

  return `/auth/login`
}

export const postAuthLogin = async (postAuthLoginBodyOne: PostAuthLoginBodyOne, options?: RequestInit): Promise<postAuthLoginResponse> => {
  
  return apiMutator<postAuthLoginResponse>(getPostAuthLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postAuthLoginBodyOne,)
  }
);}




export const getPostAuthLoginMutationOptions = <TError = PostAuthLogin401 | PostAuthLogin500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: PostAuthLoginBodyOne}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: PostAuthLoginBodyOne}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: PostAuthLoginBodyOne}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = PostAuthLoginBodyOne
    export type PostAuthLoginMutationError = PostAuthLogin401 | PostAuthLogin500

    /**
 * @summary Login user
 */
export const usePostAuthLogin = <TError = PostAuthLogin401 | PostAuthLogin500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: PostAuthLoginBodyOne}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: PostAuthLoginBodyOne},
        TContext
      > => {

      const mutationOptions = getPostAuthLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Logout user
 */
export type postAuthLogoutResponse200 = {
  data: PostAuthLogout200
  status: 200
}

export type postAuthLogoutResponse500 = {
  data: PostAuthLogout500
  status: 500
}
    
export type postAuthLogoutResponseSuccess = (postAuthLogoutResponse200) & {
  headers: Headers;
};
export type postAuthLogoutResponseError = (postAuthLogoutResponse500) & {
  headers: Headers;
};

export type postAuthLogoutResponse = (postAuthLogoutResponseSuccess | postAuthLogoutResponseError)

export const getPostAuthLogoutUrl = () => {


  

  return `/auth/logout`
}

export const postAuthLogout = async ( options?: RequestInit): Promise<postAuthLogoutResponse> => {
  
  return apiMutator<postAuthLogoutResponse>(getPostAuthLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getPostAuthLogoutMutationOptions = <TError = PostAuthLogout500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext> => {

const mutationKey = ['postAuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, void> = () => {
          

          return  postAuthLogout(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>
    
    export type PostAuthLogoutMutationError = PostAuthLogout500

    /**
 * @summary Logout user
 */
export const usePostAuthLogout = <TError = PostAuthLogout500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostAuthLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get current user
 */
export type getAuthMeResponse200 = {
  data: GetAuthMe200
  status: 200
}

export type getAuthMeResponse401 = {
  data: GetAuthMe401
  status: 401
}

export type getAuthMeResponse500 = {
  data: GetAuthMe500
  status: 500
}
    
export type getAuthMeResponseSuccess = (getAuthMeResponse200) & {
  headers: Headers;
};
export type getAuthMeResponseError = (getAuthMeResponse401 | getAuthMeResponse500) & {
  headers: Headers;
};

export type getAuthMeResponse = (getAuthMeResponseSuccess | getAuthMeResponseError)

export const getGetAuthMeUrl = () => {


  

  return `/auth/me`
}

export const getAuthMe = async ( options?: RequestInit): Promise<getAuthMeResponse> => {
  
  return apiMutator<getAuthMeResponse>(getGetAuthMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAuthMeQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }

    
export const getGetAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe401 | GetAuthMe500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthMe>>> = ({ signal }) => getAuthMe({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthMe>>>
export type GetAuthMeQueryError = GetAuthMe401 | GetAuthMe500


export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe401 | GetAuthMe500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe401 | GetAuthMe500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe401 | GetAuthMe500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user
 */

export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = GetAuthMe401 | GetAuthMe500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Initiate Google OAuth
 */
export type getApiAuthGoogleResponse302 = {
  data: void
  status: 302
}
    
;
export type getApiAuthGoogleResponseError = (getApiAuthGoogleResponse302) & {
  headers: Headers;
};

export type getApiAuthGoogleResponse = (getApiAuthGoogleResponseError)

export const getGetApiAuthGoogleUrl = () => {


  

  return `/api/auth/google/`
}

export const getApiAuthGoogle = async ( options?: RequestInit): Promise<getApiAuthGoogleResponse> => {
  
  return apiMutator<getApiAuthGoogleResponse>(getGetApiAuthGoogleUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiAuthGoogleQueryKey = () => {
    return [
    `/api/auth/google/`
    ] as const;
    }

    
export const getGetApiAuthGoogleQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthGoogle>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogle>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthGoogleQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthGoogle>>> = ({ signal }) => getApiAuthGoogle({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthGoogleQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthGoogle>>>
export type GetApiAuthGoogleQueryError = void


export function useGetApiAuthGoogle<TData = Awaited<ReturnType<typeof getApiAuthGoogle>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthGoogle>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthGoogle>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthGoogle<TData = Awaited<ReturnType<typeof getApiAuthGoogle>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthGoogle>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthGoogle>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthGoogle<TData = Awaited<ReturnType<typeof getApiAuthGoogle>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogle>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Initiate Google OAuth
 */

export function useGetApiAuthGoogle<TData = Awaited<ReturnType<typeof getApiAuthGoogle>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogle>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthGoogleQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Google OAuth callback
 */
export type getApiAuthGoogleCallbackResponse302 = {
  data: void
  status: 302
}

export type getApiAuthGoogleCallbackResponse400 = {
  data: GetApiAuthGoogleCallback400
  status: 400
}

export type getApiAuthGoogleCallbackResponse401 = {
  data: GetApiAuthGoogleCallback401
  status: 401
}

export type getApiAuthGoogleCallbackResponse500 = {
  data: GetApiAuthGoogleCallback500
  status: 500
}
    
;
export type getApiAuthGoogleCallbackResponseError = (getApiAuthGoogleCallbackResponse302 | getApiAuthGoogleCallbackResponse400 | getApiAuthGoogleCallbackResponse401 | getApiAuthGoogleCallbackResponse500) & {
  headers: Headers;
};

export type getApiAuthGoogleCallbackResponse = (getApiAuthGoogleCallbackResponseError)

export const getGetApiAuthGoogleCallbackUrl = () => {


  

  return `/api/auth/google/callback`
}

export const getApiAuthGoogleCallback = async ( options?: RequestInit): Promise<getApiAuthGoogleCallbackResponse> => {
  
  return apiMutator<getApiAuthGoogleCallbackResponse>(getGetApiAuthGoogleCallbackUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiAuthGoogleCallbackQueryKey = () => {
    return [
    `/api/auth/google/callback`
    ] as const;
    }

    
export const getGetApiAuthGoogleCallbackQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError = void | GetApiAuthGoogleCallback400 | GetApiAuthGoogleCallback401 | GetApiAuthGoogleCallback500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthGoogleCallbackQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>> = ({ signal }) => getApiAuthGoogleCallback({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthGoogleCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>>
export type GetApiAuthGoogleCallbackQueryError = void | GetApiAuthGoogleCallback400 | GetApiAuthGoogleCallback401 | GetApiAuthGoogleCallback500


export function useGetApiAuthGoogleCallback<TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError = void | GetApiAuthGoogleCallback400 | GetApiAuthGoogleCallback401 | GetApiAuthGoogleCallback500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthGoogleCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthGoogleCallback<TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError = void | GetApiAuthGoogleCallback400 | GetApiAuthGoogleCallback401 | GetApiAuthGoogleCallback500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthGoogleCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthGoogleCallback<TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError = void | GetApiAuthGoogleCallback400 | GetApiAuthGoogleCallback401 | GetApiAuthGoogleCallback500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Google OAuth callback
 */

export function useGetApiAuthGoogleCallback<TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError = void | GetApiAuthGoogleCallback400 | GetApiAuthGoogleCallback401 | GetApiAuthGoogleCallback500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthGoogleCallbackQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




