/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API Documentation
 * Production-ready backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetAuthMe200,
  GetAuthMe401,
  GetAuthMe500,
  PostAuthLogin200,
  PostAuthLogin400,
  PostAuthLogin401,
  PostAuthLogin500,
  PostAuthLoginBody,
  PostAuthLogout200,
  PostAuthLogout500,
  PostAuthRegister201,
  PostAuthRegister400,
  PostAuthRegister409,
  PostAuthRegister500,
  PostAuthRegisterBody,
} from "../../models";

import { apiMutator } from "../../apiMutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Creates a new user account. The password will be securely hashed using Argon2 before storage. Username must be unique and contain only alphanumeric characters and underscores.
 * @summary Register a new user
 */
export type postAuthRegisterResponse201 = {
  data: PostAuthRegister201;
  status: 201;
};

export type postAuthRegisterResponse400 = {
  data: PostAuthRegister400;
  status: 400;
};

export type postAuthRegisterResponse409 = {
  data: PostAuthRegister409;
  status: 409;
};

export type postAuthRegisterResponse500 = {
  data: PostAuthRegister500;
  status: 500;
};

export type postAuthRegisterResponseSuccess = postAuthRegisterResponse201 & {
  headers: Headers;
};
export type postAuthRegisterResponseError = (
  | postAuthRegisterResponse400
  | postAuthRegisterResponse409
  | postAuthRegisterResponse500
) & {
  headers: Headers;
};

export type postAuthRegisterResponse =
  | postAuthRegisterResponseSuccess
  | postAuthRegisterResponseError;

export const getPostAuthRegisterUrl = () => {
  return `/auth/register`;
};

export const postAuthRegister = async (
  postAuthRegisterBody: PostAuthRegisterBody,
  options?: RequestInit,
): Promise<postAuthRegisterResponse> => {
  return apiMutator<postAuthRegisterResponse>(getPostAuthRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postAuthRegisterBody),
  });
};

export const getPostAuthRegisterMutationOptions = <
  TError = PostAuthRegister400 | PostAuthRegister409 | PostAuthRegister500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRegister>>,
    TError,
    { data: PostAuthRegisterBody },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthRegister>>,
  TError,
  { data: PostAuthRegisterBody },
  TContext
> => {
  const mutationKey = ["postAuthRegister"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthRegister>>,
    { data: PostAuthRegisterBody }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRegister>>
>;
export type PostAuthRegisterMutationBody = PostAuthRegisterBody;
export type PostAuthRegisterMutationError =
  | PostAuthRegister400
  | PostAuthRegister409
  | PostAuthRegister500;

/**
 * @summary Register a new user
 */
export const usePostAuthRegister = <
  TError = PostAuthRegister400 | PostAuthRegister409 | PostAuthRegister500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthRegister>>,
      TError,
      { data: PostAuthRegisterBody },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthRegister>>,
  TError,
  { data: PostAuthRegisterBody },
  TContext
> => {
  const mutationOptions = getPostAuthRegisterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Authenticates a user and creates a session. The session ID is stored in an HTTP-only cookie. You can login using either username or email address.
 * @summary Login user
 */
export type postAuthLoginResponse200 = {
  data: PostAuthLogin200;
  status: 200;
};

export type postAuthLoginResponse400 = {
  data: PostAuthLogin400;
  status: 400;
};

export type postAuthLoginResponse401 = {
  data: PostAuthLogin401;
  status: 401;
};

export type postAuthLoginResponse500 = {
  data: PostAuthLogin500;
  status: 500;
};

export type postAuthLoginResponseSuccess = postAuthLoginResponse200 & {
  headers: Headers;
};
export type postAuthLoginResponseError = (
  | postAuthLoginResponse400
  | postAuthLoginResponse401
  | postAuthLoginResponse500
) & {
  headers: Headers;
};

export type postAuthLoginResponse =
  | postAuthLoginResponseSuccess
  | postAuthLoginResponseError;

export const getPostAuthLoginUrl = () => {
  return `/auth/login`;
};

export const postAuthLogin = async (
  postAuthLoginBody: PostAuthLoginBody,
  options?: RequestInit,
): Promise<postAuthLoginResponse> => {
  return apiMutator<postAuthLoginResponse>(getPostAuthLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postAuthLoginBody),
  });
};

export const getPostAuthLoginMutationOptions = <
  TError = PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    { data: PostAuthLoginBody },
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: PostAuthLoginBody },
  TContext
> => {
  const mutationKey = ["postAuthLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthLogin>>,
    { data: PostAuthLoginBody }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogin>>
>;
export type PostAuthLoginMutationBody = PostAuthLoginBody;
export type PostAuthLoginMutationError =
  | PostAuthLogin400
  | PostAuthLogin401
  | PostAuthLogin500;

/**
 * @summary Login user
 */
export const usePostAuthLogin = <
  TError = PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLogin>>,
      TError,
      { data: PostAuthLoginBody },
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: PostAuthLoginBody },
  TContext
> => {
  const mutationOptions = getPostAuthLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Logs out the current user by destroying their session and clearing the session cookie. Works even if no valid session exists.
 * @summary Logout user
 */
export type postAuthLogoutResponse200 = {
  data: PostAuthLogout200;
  status: 200;
};

export type postAuthLogoutResponse500 = {
  data: PostAuthLogout500;
  status: 500;
};

export type postAuthLogoutResponseSuccess = postAuthLogoutResponse200 & {
  headers: Headers;
};
export type postAuthLogoutResponseError = postAuthLogoutResponse500 & {
  headers: Headers;
};

export type postAuthLogoutResponse =
  | postAuthLogoutResponseSuccess
  | postAuthLogoutResponseError;

export const getPostAuthLogoutUrl = () => {
  return `/auth/logout`;
};

export const postAuthLogout = async (
  options?: RequestInit,
): Promise<postAuthLogoutResponse> => {
  return apiMutator<postAuthLogoutResponse>(getPostAuthLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const getPostAuthLogoutMutationOptions = <
  TError = PostAuthLogout500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof apiMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postAuthLogout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthLogout>>,
    void
  > = () => {
    return postAuthLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogout>>
>;

export type PostAuthLogoutMutationError = PostAuthLogout500;

/**
 * @summary Logout user
 */
export const usePostAuthLogout = <
  TError = PostAuthLogout500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLogout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPostAuthLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves the currently authenticated user's information based on their session cookie. The session TTL is automatically extended on successful requests.
 * @summary Get current user
 */
export type getAuthMeResponse200 = {
  data: GetAuthMe200;
  status: 200;
};

export type getAuthMeResponse401 = {
  data: GetAuthMe401;
  status: 401;
};

export type getAuthMeResponse500 = {
  data: GetAuthMe500;
  status: 500;
};

export type getAuthMeResponseSuccess = getAuthMeResponse200 & {
  headers: Headers;
};
export type getAuthMeResponseError = (
  | getAuthMeResponse401
  | getAuthMeResponse500
) & {
  headers: Headers;
};

export type getAuthMeResponse =
  | getAuthMeResponseSuccess
  | getAuthMeResponseError;

export const getGetAuthMeUrl = () => {
  return `/auth/me`;
};

export const getAuthMe = async (
  options?: RequestInit,
): Promise<getAuthMeResponse> => {
  return apiMutator<getAuthMeResponse>(getGetAuthMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAuthMeQueryKey = () => {
  return [`/auth/me`] as const;
};

export const getGetAuthMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GetAuthMe401 | GetAuthMe500,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof apiMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthMe>>> = ({
    signal,
  }) => getAuthMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthMe>>
>;
export type GetAuthMeQueryError = GetAuthMe401 | GetAuthMe500;

export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GetAuthMe401 | GetAuthMe500,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GetAuthMe401 | GetAuthMe500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GetAuthMe401 | GetAuthMe500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user
 */

export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = GetAuthMe401 | GetAuthMe500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAuthMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
