/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API - Authentication
 * REST API для автентифікації користувачів.

⚠️ **Note**: Всі інші endpoints доступні через GraphQL API. Використовуйте GraphiQL Playground на `/graphql` для GraphQL API документації.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetHealth200,
  GetHealth405,
  GetIndex200,
  GetIndex405
} from '../../models';

import { apiMutator } from '../../apiMutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the current health status of the API and a timestamp. Useful for monitoring and load balancer health checks.
 * @summary Health check
 */
export type getHealthResponse200 = {
  data: GetHealth200
  status: 200
}

export type getHealthResponse405 = {
  data: GetHealth405
  status: 405
}
    
export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
export type getHealthResponseError = (getHealthResponse405) & {
  headers: Headers;
};

export type getHealthResponse = (getHealthResponseSuccess | getHealthResponseError)

export const getGetHealthUrl = () => {


  

  return `/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {
  
  return apiMutator<getHealthResponse>(getGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }

    
export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = GetHealth405>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = GetHealth405


export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = GetHealth405>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = GetHealth405>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = GetHealth405>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health check
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = GetHealth405>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns basic API information including version, message, and links to documentation, GraphQL endpoint, and health check endpoint.
 * @summary API information
 */
export type getIndexResponse200 = {
  data: GetIndex200
  status: 200
}

export type getIndexResponse405 = {
  data: GetIndex405
  status: 405
}
    
export type getIndexResponseSuccess = (getIndexResponse200) & {
  headers: Headers;
};
export type getIndexResponseError = (getIndexResponse405) & {
  headers: Headers;
};

export type getIndexResponse = (getIndexResponseSuccess | getIndexResponseError)

export const getGetIndexUrl = () => {


  

  return `/`
}

export const getIndex = async ( options?: RequestInit): Promise<getIndexResponse> => {
  
  return apiMutator<getIndexResponse>(getGetIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetIndexQueryKey = () => {
    return [
    `/`
    ] as const;
    }

    
export const getGetIndexQueryOptions = <TData = Awaited<ReturnType<typeof getIndex>>, TError = GetIndex405>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIndex>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIndex>>> = ({ signal }) => getIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIndexQueryResult = NonNullable<Awaited<ReturnType<typeof getIndex>>>
export type GetIndexQueryError = GetIndex405


export function useGetIndex<TData = Awaited<ReturnType<typeof getIndex>>, TError = GetIndex405>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIndex>>,
          TError,
          Awaited<ReturnType<typeof getIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIndex<TData = Awaited<ReturnType<typeof getIndex>>, TError = GetIndex405>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIndex>>,
          TError,
          Awaited<ReturnType<typeof getIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIndex<TData = Awaited<ReturnType<typeof getIndex>>, TError = GetIndex405>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIndex>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary API information
 */

export function useGetIndex<TData = Awaited<ReturnType<typeof getIndex>>, TError = GetIndex405>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIndex>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




