/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root";
import { Route as MainRouteImport } from "./pages/_main";
import { Route as AuthRouteImport } from "./pages/_auth";
import { Route as MainIndexRouteImport } from "./pages/_main.index";
import { Route as MainSubmitRouteImport } from "./pages/_main.submit";
import { Route as MainSettingsRouteImport } from "./pages/_main.settings";
import { Route as MainSearchRouteImport } from "./pages/_main.search";
import { Route as MainSavedRouteImport } from "./pages/_main.saved";
import { Route as MainNotificationsRouteImport } from "./pages/_main.notifications";
import { Route as MainAuthenticatedRouteImport } from "./pages/_main._authenticated";
import { Route as AuthResetRouteImport } from "./pages/_auth.reset";
import { Route as AuthRegisterRouteImport } from "./pages/_auth.register";
import { Route as AuthLoginRouteImport } from "./pages/_auth.login";
import { Route as MainUUsernameRouteImport } from "./pages/_main.u.$username";
import { Route as MainRCommunityIdRouteImport } from "./pages/_main.r.$communityId";
import { Route as MainPostPostIdRouteImport } from "./pages/_main.post.$postId";

const MainRoute = MainRouteImport.update({
  id: "/_main",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const MainIndexRoute = MainIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MainRoute,
} as any);
const MainSubmitRoute = MainSubmitRouteImport.update({
  id: "/submit",
  path: "/submit",
  getParentRoute: () => MainRoute,
} as any);
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => MainRoute,
} as any);
const MainSearchRoute = MainSearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => MainRoute,
} as any);
const MainSavedRoute = MainSavedRouteImport.update({
  id: "/saved",
  path: "/saved",
  getParentRoute: () => MainRoute,
} as any);
const MainNotificationsRoute = MainNotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => MainRoute,
} as any);
const MainAuthenticatedRoute = MainAuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => MainRoute,
} as any);
const AuthResetRoute = AuthResetRouteImport.update({
  id: "/reset",
  path: "/reset",
  getParentRoute: () => AuthRoute,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any);
const MainUUsernameRoute = MainUUsernameRouteImport.update({
  id: "/u/$username",
  path: "/u/$username",
  getParentRoute: () => MainRoute,
} as any);
const MainRCommunityIdRoute = MainRCommunityIdRouteImport.update({
  id: "/r/$communityId",
  path: "/r/$communityId",
  getParentRoute: () => MainRoute,
} as any);
const MainPostPostIdRoute = MainPostPostIdRouteImport.update({
  id: "/post/$postId",
  path: "/post/$postId",
  getParentRoute: () => MainRoute,
} as any);

export interface FileRoutesByFullPath {
  "/login": typeof AuthLoginRoute;
  "/register": typeof AuthRegisterRoute;
  "/reset": typeof AuthResetRoute;
  "/notifications": typeof MainNotificationsRoute;
  "/saved": typeof MainSavedRoute;
  "/search": typeof MainSearchRoute;
  "/settings": typeof MainSettingsRoute;
  "/submit": typeof MainSubmitRoute;
  "/": typeof MainIndexRoute;
  "/post/$postId": typeof MainPostPostIdRoute;
  "/r/$communityId": typeof MainRCommunityIdRoute;
  "/u/$username": typeof MainUUsernameRoute;
}
export interface FileRoutesByTo {
  "/login": typeof AuthLoginRoute;
  "/register": typeof AuthRegisterRoute;
  "/reset": typeof AuthResetRoute;
  "/notifications": typeof MainNotificationsRoute;
  "/saved": typeof MainSavedRoute;
  "/search": typeof MainSearchRoute;
  "/settings": typeof MainSettingsRoute;
  "/submit": typeof MainSubmitRoute;
  "/": typeof MainIndexRoute;
  "/post/$postId": typeof MainPostPostIdRoute;
  "/r/$communityId": typeof MainRCommunityIdRoute;
  "/u/$username": typeof MainUUsernameRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteWithChildren;
  "/_main": typeof MainRouteWithChildren;
  "/_auth/login": typeof AuthLoginRoute;
  "/_auth/register": typeof AuthRegisterRoute;
  "/_auth/reset": typeof AuthResetRoute;
  "/_main/_authenticated": typeof MainAuthenticatedRoute;
  "/_main/notifications": typeof MainNotificationsRoute;
  "/_main/saved": typeof MainSavedRoute;
  "/_main/search": typeof MainSearchRoute;
  "/_main/settings": typeof MainSettingsRoute;
  "/_main/submit": typeof MainSubmitRoute;
  "/_main/": typeof MainIndexRoute;
  "/_main/post/$postId": typeof MainPostPostIdRoute;
  "/_main/r/$communityId": typeof MainRCommunityIdRoute;
  "/_main/u/$username": typeof MainUUsernameRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/login"
    | "/register"
    | "/reset"
    | "/notifications"
    | "/saved"
    | "/search"
    | "/settings"
    | "/submit"
    | "/"
    | "/post/$postId"
    | "/r/$communityId"
    | "/u/$username";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/register"
    | "/reset"
    | "/notifications"
    | "/saved"
    | "/search"
    | "/settings"
    | "/submit"
    | "/"
    | "/post/$postId"
    | "/r/$communityId"
    | "/u/$username";
  id:
    | "__root__"
    | "/_auth"
    | "/_main"
    | "/_auth/login"
    | "/_auth/register"
    | "/_auth/reset"
    | "/_main/_authenticated"
    | "/_main/notifications"
    | "/_main/saved"
    | "/_main/search"
    | "/_main/settings"
    | "/_main/submit"
    | "/_main/"
    | "/_main/post/$postId"
    | "/_main/r/$communityId"
    | "/_main/u/$username";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  MainRoute: typeof MainRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_main": {
      id: "/_main";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof MainRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_main/": {
      id: "/_main/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof MainIndexRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/submit": {
      id: "/_main/submit";
      path: "/submit";
      fullPath: "/submit";
      preLoaderRoute: typeof MainSubmitRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/settings": {
      id: "/_main/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof MainSettingsRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/search": {
      id: "/_main/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof MainSearchRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/saved": {
      id: "/_main/saved";
      path: "/saved";
      fullPath: "/saved";
      preLoaderRoute: typeof MainSavedRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/notifications": {
      id: "/_main/notifications";
      path: "/notifications";
      fullPath: "/notifications";
      preLoaderRoute: typeof MainNotificationsRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/_authenticated": {
      id: "/_main/_authenticated";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof MainAuthenticatedRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_auth/reset": {
      id: "/_auth/reset";
      path: "/reset";
      fullPath: "/reset";
      preLoaderRoute: typeof AuthResetRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/register": {
      id: "/_auth/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/login": {
      id: "/_auth/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_main/u/$username": {
      id: "/_main/u/$username";
      path: "/u/$username";
      fullPath: "/u/$username";
      preLoaderRoute: typeof MainUUsernameRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/r/$communityId": {
      id: "/_main/r/$communityId";
      path: "/r/$communityId";
      fullPath: "/r/$communityId";
      preLoaderRoute: typeof MainRCommunityIdRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/post/$postId": {
      id: "/_main/post/$postId";
      path: "/post/$postId";
      fullPath: "/post/$postId";
      preLoaderRoute: typeof MainPostPostIdRouteImport;
      parentRoute: typeof MainRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
  AuthResetRoute: typeof AuthResetRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

interface MainRouteChildren {
  MainAuthenticatedRoute: typeof MainAuthenticatedRoute;
  MainNotificationsRoute: typeof MainNotificationsRoute;
  MainSavedRoute: typeof MainSavedRoute;
  MainSearchRoute: typeof MainSearchRoute;
  MainSettingsRoute: typeof MainSettingsRoute;
  MainSubmitRoute: typeof MainSubmitRoute;
  MainIndexRoute: typeof MainIndexRoute;
  MainPostPostIdRoute: typeof MainPostPostIdRoute;
  MainRCommunityIdRoute: typeof MainRCommunityIdRoute;
  MainUUsernameRoute: typeof MainUUsernameRoute;
}

const MainRouteChildren: MainRouteChildren = {
  MainAuthenticatedRoute: MainAuthenticatedRoute,
  MainNotificationsRoute: MainNotificationsRoute,
  MainSavedRoute: MainSavedRoute,
  MainSearchRoute: MainSearchRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainSubmitRoute: MainSubmitRoute,
  MainIndexRoute: MainIndexRoute,
  MainPostPostIdRoute: MainPostPostIdRoute,
  MainRCommunityIdRoute: MainRCommunityIdRoute,
  MainUUsernameRoute: MainUUsernameRoute,
};

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
