/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as MainRouteImport } from './pages/_main'
import { Route as AuthRouteImport } from './pages/_auth'
import { Route as HomeIndexRouteImport } from './pages/home/index'
import { Route as MainIndexRouteImport } from './pages/_main.index'
import { Route as MainSubmitRouteImport } from './pages/_main.submit'
import { Route as AuthRegisterRouteImport } from './pages/_auth.register'
import { Route as AuthLoginRouteImport } from './pages/_auth.login'
import { Route as MainRCommunityIdRouteImport } from './pages/_main.r.$communityId'
import { Route as MainPostPostIdRouteImport } from './pages/_main.post.$postId'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainSubmitRoute = MainSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => MainRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MainRCommunityIdRoute = MainRCommunityIdRouteImport.update({
  id: '/r/$communityId',
  path: '/r/$communityId',
  getParentRoute: () => MainRoute,
} as any)
const MainPostPostIdRoute = MainPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/submit': typeof MainSubmitRoute
  '/': typeof MainIndexRoute
  '/home': typeof HomeIndexRoute
  '/post/$postId': typeof MainPostPostIdRoute
  '/r/$communityId': typeof MainRCommunityIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/submit': typeof MainSubmitRoute
  '/': typeof MainIndexRoute
  '/home': typeof HomeIndexRoute
  '/post/$postId': typeof MainPostPostIdRoute
  '/r/$communityId': typeof MainRCommunityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_main/submit': typeof MainSubmitRoute
  '/_main/': typeof MainIndexRoute
  '/home/': typeof HomeIndexRoute
  '/_main/post/$postId': typeof MainPostPostIdRoute
  '/_main/r/$communityId': typeof MainRCommunityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/submit'
    | '/'
    | '/home'
    | '/post/$postId'
    | '/r/$communityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/submit'
    | '/'
    | '/home'
    | '/post/$postId'
    | '/r/$communityId'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/login'
    | '/_auth/register'
    | '/_main/submit'
    | '/_main/'
    | '/home/'
    | '/_main/post/$postId'
    | '/_main/r/$communityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/submit': {
      id: '/_main/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof MainSubmitRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/r/$communityId': {
      id: '/_main/r/$communityId'
      path: '/r/$communityId'
      fullPath: '/r/$communityId'
      preLoaderRoute: typeof MainRCommunityIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/post/$postId': {
      id: '/_main/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof MainPostPostIdRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainSubmitRoute: typeof MainSubmitRoute
  MainIndexRoute: typeof MainIndexRoute
  MainPostPostIdRoute: typeof MainPostPostIdRoute
  MainRCommunityIdRoute: typeof MainRCommunityIdRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainSubmitRoute: MainSubmitRoute,
  MainIndexRoute: MainIndexRoute,
  MainPostPostIdRoute: MainPostPostIdRoute,
  MainRCommunityIdRoute: MainRCommunityIdRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
