/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API
 * Modern backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.

⚠️ **Note**: GraphQL endpoints are not included in this REST API documentation. Use GraphiQL Playground at `/graphql` for GraphQL API documentation.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetPostsParams,
  PostPostsBodyOne,
  PutPostsByIdVoteBodyOne
} from '../../models';

import { apiMutator } from '../../apiMutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieves a paginated list of all posts
 * @summary Get all posts
 */
export type getPostsResponseDefault = {
  data: unknown
  status: number
}
    
;
export type getPostsResponseError = (getPostsResponseDefault) & {
  headers: Headers;
};

export type getPostsResponse = (getPostsResponseError)

export const getGetPostsUrl = (params?: GetPostsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/posts/?${stringifiedParams}` : `/posts/`
}

export const getPosts = async (params?: GetPostsParams, options?: RequestInit): Promise<getPostsResponse> => {
  
  return apiMutator<getPostsResponse>(getGetPostsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPostsQueryKey = (params?: GetPostsParams,) => {
    return [
    `/posts/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetPostsQueryOptions = <TData = Awaited<ReturnType<typeof getPosts>>, TError = unknown>(params?: GetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosts>>> = ({ signal }) => getPosts(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostsQueryResult = NonNullable<Awaited<ReturnType<typeof getPosts>>>
export type GetPostsQueryError = unknown


export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = unknown>(
 params: undefined |  GetPostsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = unknown>(
 params?: GetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = unknown>(
 params?: GetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all posts
 */

export function useGetPosts<TData = Awaited<ReturnType<typeof getPosts>>, TError = unknown>(
 params?: GetPostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPostsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Creates a new post
 * @summary Create post
 */
export type postPostsResponseDefault = {
  data: unknown
  status: number
}
    
;
export type postPostsResponseError = (postPostsResponseDefault) & {
  headers: Headers;
};

export type postPostsResponse = (postPostsResponseError)

export const getPostPostsUrl = () => {


  

  return `/posts/`
}

export const postPosts = async (postPostsBodyOne: PostPostsBodyOne, options?: RequestInit): Promise<postPostsResponse> => {
  
  return apiMutator<postPostsResponse>(getPostPostsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postPostsBodyOne,)
  }
);}




export const getPostPostsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPosts>>, TError,{data: PostPostsBodyOne}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postPosts>>, TError,{data: PostPostsBodyOne}, TContext> => {

const mutationKey = ['postPosts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPosts>>, {data: PostPostsBodyOne}> = (props) => {
          const {data} = props ?? {};

          return  postPosts(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostPostsMutationResult = NonNullable<Awaited<ReturnType<typeof postPosts>>>
    export type PostPostsMutationBody = PostPostsBodyOne
    export type PostPostsMutationError = unknown

    /**
 * @summary Create post
 */
export const usePostPosts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPosts>>, TError,{data: PostPostsBodyOne}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postPosts>>,
        TError,
        {data: PostPostsBodyOne},
        TContext
      > => {

      const mutationOptions = getPostPostsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieves a specific post with all relations
 * @summary Get post by ID
 */
export type getPostsByIdResponseDefault = {
  data: unknown
  status: number
}
    
;
export type getPostsByIdResponseError = (getPostsByIdResponseDefault) & {
  headers: Headers;
};

export type getPostsByIdResponse = (getPostsByIdResponseError)

export const getGetPostsByIdUrl = (id: string,) => {


  

  return `/posts/${id}`
}

export const getPostsById = async (id: string, options?: RequestInit): Promise<getPostsByIdResponse> => {
  
  return apiMutator<getPostsByIdResponse>(getGetPostsByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPostsByIdQueryKey = (id?: string,) => {
    return [
    `/posts/${id}`
    ] as const;
    }

    
export const getGetPostsByIdQueryOptions = <TData = Awaited<ReturnType<typeof getPostsById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsById>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostsByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostsById>>> = ({ signal }) => getPostsById(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPostsById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPostsByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPostsById>>>
export type GetPostsByIdQueryError = unknown


export function useGetPostsById<TData = Awaited<ReturnType<typeof getPostsById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsById>>,
          TError,
          Awaited<ReturnType<typeof getPostsById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostsById<TData = Awaited<ReturnType<typeof getPostsById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsById>>,
          TError,
          Awaited<ReturnType<typeof getPostsById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPostsById<TData = Awaited<ReturnType<typeof getPostsById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsById>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get post by ID
 */

export function useGetPostsById<TData = Awaited<ReturnType<typeof getPostsById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsById>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPostsByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Upvote or downvote a post
 * @summary Vote on post
 */
export type putPostsByIdVoteResponseDefault = {
  data: unknown
  status: number
}
    
;
export type putPostsByIdVoteResponseError = (putPostsByIdVoteResponseDefault) & {
  headers: Headers;
};

export type putPostsByIdVoteResponse = (putPostsByIdVoteResponseError)

export const getPutPostsByIdVoteUrl = (id: string,) => {


  

  return `/posts/${id}/vote`
}

export const putPostsByIdVote = async (id: string,
    putPostsByIdVoteBodyOne: PutPostsByIdVoteBodyOne, options?: RequestInit): Promise<putPostsByIdVoteResponse> => {
  
  return apiMutator<putPostsByIdVoteResponse>(getPutPostsByIdVoteUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putPostsByIdVoteBodyOne,)
  }
);}




export const getPutPostsByIdVoteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putPostsByIdVote>>, TError,{id: string;data: PutPostsByIdVoteBodyOne}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putPostsByIdVote>>, TError,{id: string;data: PutPostsByIdVoteBodyOne}, TContext> => {

const mutationKey = ['putPostsByIdVote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putPostsByIdVote>>, {id: string;data: PutPostsByIdVoteBodyOne}> = (props) => {
          const {id,data} = props ?? {};

          return  putPostsByIdVote(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutPostsByIdVoteMutationResult = NonNullable<Awaited<ReturnType<typeof putPostsByIdVote>>>
    export type PutPostsByIdVoteMutationBody = PutPostsByIdVoteBodyOne
    export type PutPostsByIdVoteMutationError = unknown

    /**
 * @summary Vote on post
 */
export const usePutPostsByIdVote = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putPostsByIdVote>>, TError,{id: string;data: PutPostsByIdVoteBodyOne}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putPostsByIdVote>>,
        TError,
        {id: string;data: PutPostsByIdVoteBodyOne},
        TContext
      > => {

      const mutationOptions = getPutPostsByIdVoteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Saves a post for later
 * @summary Save post
 */
export type postPostsByIdSaveResponseDefault = {
  data: unknown
  status: number
}
    
;
export type postPostsByIdSaveResponseError = (postPostsByIdSaveResponseDefault) & {
  headers: Headers;
};

export type postPostsByIdSaveResponse = (postPostsByIdSaveResponseError)

export const getPostPostsByIdSaveUrl = (id: string,) => {


  

  return `/posts/${id}/save`
}

export const postPostsByIdSave = async (id: string, options?: RequestInit): Promise<postPostsByIdSaveResponse> => {
  
  return apiMutator<postPostsByIdSaveResponse>(getPostPostsByIdSaveUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getPostPostsByIdSaveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPostsByIdSave>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postPostsByIdSave>>, TError,{id: string}, TContext> => {

const mutationKey = ['postPostsByIdSave'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPostsByIdSave>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postPostsByIdSave(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostPostsByIdSaveMutationResult = NonNullable<Awaited<ReturnType<typeof postPostsByIdSave>>>
    
    export type PostPostsByIdSaveMutationError = unknown

    /**
 * @summary Save post
 */
export const usePostPostsByIdSave = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPostsByIdSave>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postPostsByIdSave>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPostPostsByIdSaveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Removes a post from saved posts
 * @summary Unsave post
 */
export type deletePostsByIdSaveResponseDefault = {
  data: unknown
  status: number
}
    
;
export type deletePostsByIdSaveResponseError = (deletePostsByIdSaveResponseDefault) & {
  headers: Headers;
};

export type deletePostsByIdSaveResponse = (deletePostsByIdSaveResponseError)

export const getDeletePostsByIdSaveUrl = (id: string,) => {


  

  return `/posts/${id}/save`
}

export const deletePostsByIdSave = async (id: string, options?: RequestInit): Promise<deletePostsByIdSaveResponse> => {
  
  return apiMutator<deletePostsByIdSaveResponse>(getDeletePostsByIdSaveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeletePostsByIdSaveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePostsByIdSave>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePostsByIdSave>>, TError,{id: string}, TContext> => {

const mutationKey = ['deletePostsByIdSave'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePostsByIdSave>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deletePostsByIdSave(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePostsByIdSaveMutationResult = NonNullable<Awaited<ReturnType<typeof deletePostsByIdSave>>>
    
    export type DeletePostsByIdSaveMutationError = unknown

    /**
 * @summary Unsave post
 */
export const useDeletePostsByIdSave = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePostsByIdSave>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePostsByIdSave>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeletePostsByIdSaveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    