/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API
 * Modern backend API built with Elysia.js, Drizzle ORM, and PostgreSQL. Provides user management, authentication, and health monitoring endpoints.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { apiMutator } from '../../apiMutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getGraphqlResponseDefault = {
  data: unknown
  status: number
}
    
;
export type getGraphqlResponseError = (getGraphqlResponseDefault) & {
  headers: Headers;
};

export type getGraphqlResponse = (getGraphqlResponseError)

export const getGetGraphqlUrl = () => {


  

  return `/graphql`
}

export const getGraphql = async ( options?: RequestInit): Promise<getGraphqlResponse> => {
  
  return apiMutator<getGraphqlResponse>(getGetGraphqlUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetGraphqlQueryKey = () => {
    return [
    `/graphql`
    ] as const;
    }

    
export const getGetGraphqlQueryOptions = <TData = Awaited<ReturnType<typeof getGraphql>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphql>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGraphqlQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGraphql>>> = ({ signal }) => getGraphql({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGraphql>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGraphqlQueryResult = NonNullable<Awaited<ReturnType<typeof getGraphql>>>
export type GetGraphqlQueryError = unknown


export function useGetGraphql<TData = Awaited<ReturnType<typeof getGraphql>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphql>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGraphql>>,
          TError,
          Awaited<ReturnType<typeof getGraphql>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGraphql<TData = Awaited<ReturnType<typeof getGraphql>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphql>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGraphql>>,
          TError,
          Awaited<ReturnType<typeof getGraphql>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGraphql<TData = Awaited<ReturnType<typeof getGraphql>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphql>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGraphql<TData = Awaited<ReturnType<typeof getGraphql>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphql>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGraphqlQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export type postGraphqlResponseDefault = {
  data: unknown
  status: number
}
    
;
export type postGraphqlResponseError = (postGraphqlResponseDefault) & {
  headers: Headers;
};

export type postGraphqlResponse = (postGraphqlResponseError)

export const getPostGraphqlUrl = () => {


  

  return `/graphql`
}

export const postGraphql = async ( options?: RequestInit): Promise<postGraphqlResponse> => {
  
  return apiMutator<postGraphqlResponse>(getPostGraphqlUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getPostGraphqlMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postGraphql>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postGraphql>>, TError,void, TContext> => {

const mutationKey = ['postGraphql'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postGraphql>>, void> = () => {
          

          return  postGraphql(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostGraphqlMutationResult = NonNullable<Awaited<ReturnType<typeof postGraphql>>>
    
    export type PostGraphqlMutationError = unknown

    export const usePostGraphql = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postGraphql>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postGraphql>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostGraphqlMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type allHealthResponseDefault = {
  data: unknown
  status: number
}
    
;
export type allHealthResponseError = (allHealthResponseDefault) & {
  headers: Headers;
};

export type allHealthResponse = (allHealthResponseError)

export const getAllHealthUrl = () => {


  

  return `/health`
}

export const allHealth = async ( options?: RequestInit): Promise<allHealthResponse> => {
  
  return apiMutator<allHealthResponse>(getAllHealthUrl(),
  {      
    ...options,
    method: 'HEAD'
    
    
  }
);}




export const getAllHealthMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof allHealth>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof allHealth>>, TError,void, TContext> => {

const mutationKey = ['allHealth'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof allHealth>>, void> = () => {
          

          return  allHealth(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AllHealthMutationResult = NonNullable<Awaited<ReturnType<typeof allHealth>>>
    
    export type AllHealthMutationError = unknown

    export const useAllHealth = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof allHealth>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof allHealth>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAllHealthMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type allIndexResponseDefault = {
  data: unknown
  status: number
}
    
;
export type allIndexResponseError = (allIndexResponseDefault) & {
  headers: Headers;
};

export type allIndexResponse = (allIndexResponseError)

export const getAllIndexUrl = () => {


  

  return `/`
}

export const allIndex = async ( options?: RequestInit): Promise<allIndexResponse> => {
  
  return apiMutator<allIndexResponse>(getAllIndexUrl(),
  {      
    ...options,
    method: 'HEAD'
    
    
  }
);}




export const getAllIndexMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof allIndex>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof allIndex>>, TError,void, TContext> => {

const mutationKey = ['allIndex'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof allIndex>>, void> = () => {
          

          return  allIndex(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AllIndexMutationResult = NonNullable<Awaited<ReturnType<typeof allIndex>>>
    
    export type AllIndexMutationError = unknown

    export const useAllIndex = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof allIndex>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof allIndex>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAllIndexMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type getApiAuthGoogleResponseDefault = {
  data: unknown
  status: number
}
    
;
export type getApiAuthGoogleResponseError = (getApiAuthGoogleResponseDefault) & {
  headers: Headers;
};

export type getApiAuthGoogleResponse = (getApiAuthGoogleResponseError)

export const getGetApiAuthGoogleUrl = () => {


  

  return `/api/auth/google/`
}

export const getApiAuthGoogle = async ( options?: RequestInit): Promise<getApiAuthGoogleResponse> => {
  
  return apiMutator<getApiAuthGoogleResponse>(getGetApiAuthGoogleUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiAuthGoogleQueryKey = () => {
    return [
    `/api/auth/google/`
    ] as const;
    }

    
export const getGetApiAuthGoogleQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthGoogle>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogle>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthGoogleQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthGoogle>>> = ({ signal }) => getApiAuthGoogle({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthGoogleQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthGoogle>>>
export type GetApiAuthGoogleQueryError = unknown


export function useGetApiAuthGoogle<TData = Awaited<ReturnType<typeof getApiAuthGoogle>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthGoogle>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthGoogle>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthGoogle<TData = Awaited<ReturnType<typeof getApiAuthGoogle>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthGoogle>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthGoogle>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthGoogle<TData = Awaited<ReturnType<typeof getApiAuthGoogle>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogle>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthGoogle<TData = Awaited<ReturnType<typeof getApiAuthGoogle>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogle>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthGoogleQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export type getApiAuthGoogleCallbackResponseDefault = {
  data: unknown
  status: number
}
    
;
export type getApiAuthGoogleCallbackResponseError = (getApiAuthGoogleCallbackResponseDefault) & {
  headers: Headers;
};

export type getApiAuthGoogleCallbackResponse = (getApiAuthGoogleCallbackResponseError)

export const getGetApiAuthGoogleCallbackUrl = () => {


  

  return `/api/auth/google/callback`
}

export const getApiAuthGoogleCallback = async ( options?: RequestInit): Promise<getApiAuthGoogleCallbackResponse> => {
  
  return apiMutator<getApiAuthGoogleCallbackResponse>(getGetApiAuthGoogleCallbackUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiAuthGoogleCallbackQueryKey = () => {
    return [
    `/api/auth/google/callback`
    ] as const;
    }

    
export const getGetApiAuthGoogleCallbackQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthGoogleCallbackQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>> = ({ signal }) => getApiAuthGoogleCallback({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthGoogleCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>>
export type GetApiAuthGoogleCallbackQueryError = unknown


export function useGetApiAuthGoogleCallback<TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthGoogleCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthGoogleCallback<TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthGoogleCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthGoogleCallback<TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthGoogleCallback<TData = Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthGoogleCallback>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthGoogleCallbackQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




