/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Reddit Backend API - Authentication
 * REST API для автентифікації користувачів.

⚠️ **Note**: Всі інші endpoints доступні через GraphQL API. Використовуйте GraphiQL Playground на `/graphql` для GraphQL API документації.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { apiMutator } from '../../apiMutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getGraphqlResponseDefault = {
  data: unknown
  status: number
}
    
;
export type getGraphqlResponseError = (getGraphqlResponseDefault) & {
  headers: Headers;
};

export type getGraphqlResponse = (getGraphqlResponseError)

export const getGetGraphqlUrl = () => {


  

  return `/graphql`
}

export const getGraphql = async ( options?: RequestInit): Promise<getGraphqlResponse> => {
  
  return apiMutator<getGraphqlResponse>(getGetGraphqlUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetGraphqlQueryKey = () => {
    return [
    `/graphql`
    ] as const;
    }

    
export const getGetGraphqlQueryOptions = <TData = Awaited<ReturnType<typeof getGraphql>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphql>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGraphqlQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGraphql>>> = ({ signal }) => getGraphql({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGraphql>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGraphqlQueryResult = NonNullable<Awaited<ReturnType<typeof getGraphql>>>
export type GetGraphqlQueryError = unknown


export function useGetGraphql<TData = Awaited<ReturnType<typeof getGraphql>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphql>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGraphql>>,
          TError,
          Awaited<ReturnType<typeof getGraphql>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGraphql<TData = Awaited<ReturnType<typeof getGraphql>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphql>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGraphql>>,
          TError,
          Awaited<ReturnType<typeof getGraphql>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGraphql<TData = Awaited<ReturnType<typeof getGraphql>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphql>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGraphql<TData = Awaited<ReturnType<typeof getGraphql>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphql>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGraphqlQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export type postGraphqlResponseDefault = {
  data: unknown
  status: number
}
    
;
export type postGraphqlResponseError = (postGraphqlResponseDefault) & {
  headers: Headers;
};

export type postGraphqlResponse = (postGraphqlResponseError)

export const getPostGraphqlUrl = () => {


  

  return `/graphql`
}

export const postGraphql = async ( options?: RequestInit): Promise<postGraphqlResponse> => {
  
  return apiMutator<postGraphqlResponse>(getPostGraphqlUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getPostGraphqlMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postGraphql>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postGraphql>>, TError,void, TContext> => {

const mutationKey = ['postGraphql'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postGraphql>>, void> = () => {
          

          return  postGraphql(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostGraphqlMutationResult = NonNullable<Awaited<ReturnType<typeof postGraphql>>>
    
    export type PostGraphqlMutationError = unknown

    export const usePostGraphql = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postGraphql>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postGraphql>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostGraphqlMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    